name = "opentuware"
compatibility_date = "2025-01-01"
pages_build_output_dir = "dist"

[ai]
binding = "AI"

[[vectorize]]
binding = "VECTORIZE_TEXT"
index_name = "tuwa-brain"

[[vectorize]]
binding = "VECTORIZE_VISION"
index_name = "tuwa-vision"

[[d1_databases]]
binding = "DB"
database_name = "articles"
database_id = "5494913d-dde9-48ae-82a4-5774ed2b11a6"