pages_build_output_dir = "dist"

[ai]
binding = "AI"

[[vectorize]]
binding = "VECTORIZE"
index_name = "tuwa-brain"

# Add your D1 database binding here!
[[d1_databases]]
binding = "DB"
database_name = "articles"
database_id = "5494913d-dde9-48ae-82a4-5774ed2b11a6"